// Generated by https://quicktype.io

export interface AuthenticateResponse {
    user: User;
    menu: ItemMenu[];
}

export interface ItemMenu {
    label: string;
    can: boolean;
    route: string;
}

export interface User {
    id: number;
    name: string;
    email: string;
    email_verified_at: string;
    created_at: string;
    updated_at: string;
    permissions: any[];
    roles: Role[];
}

export interface Role {
    id: number;
    name: string;
    guard_name: string;
    created_at: string;
    updated_at: string;
    pivot: Pivot;
}

export interface Pivot {
    model_id: number;
    role_id: number;
    model_type: string;
}