// Generated by https://quicktype.io

export interface EnrollStudentDto {
  student_id?: number;
  name: string;
  dni: string;
  email: string;
  department_id: number;
  address: string;
  phone: string;
  cellphone: string;
  date_of_birth: string;
  observation: string;
  course_id: number;
  course_turn_id: number;
  start_date: string;
  registered_by: number;
  enrolled_by: number;
  payment: Payment;
  transaction: Transaction;
}

export interface Payment {
  type: number;
  observation?: string;
  amount: number;
  enroll_amount?: number;
  pay_enroll_amount?: number;
  installments?: Installment[];
}

export interface Installment {
  amount: number;
  pay?: number;
}

export interface Transaction {
  bank_id: number;
  operation: string;
  user_id: number;
}
