// Generated by https://quicktype.io

import { User } from 'src/app/users/interfaces/user.interface';

export interface Operation {
  id: number;
  name: null;
  payment_date: string;
  bank_id: number;
  user_id: number;
  operation: string;
  created_at: string;
  updated_at: string;
  bank: Bank;
  payment: Payment;
  damping?: Damping;
  responsable: User;
}

// Generated by https://quicktype.io

export interface Damping {
  id: number;
  amount: number;
  voucher: string;
  transaction_id: number;
  installment_id: number;
  created_at: string;
  updated_at: string;
  installment: Installment;
}

export interface Installment {
  id: number;
  number: null;
  type: string;
  amount: number;
  balance: number;
  late: number;
  observation: null;
  payment_id: number;
  created_at: string;
  updated_at: string;
  payment: Payment;
}

export interface Payment {
  id: number;
  amount: number;
  type: number;
  voucher: null;
  observation: null;
  transaction_id: null;
  created_at: string;
  updated_at: string;
  course_turn_student: CourseTurnStudent;
}

export interface CourseTurnStudent {
  id: number;
  student_id: number;
  course_turn_id: number;
  enrolled_by: number;
  payment_id: number;
  start_date: string;
  created_at: string;
  updated_at: string;
  student: Student;
}

export interface Student {
  id: number;
  name: string;
  dni: string;
  email: string;
  department_id: number;
  address: string;
  phone: string;
  cellphone: string;
  date_of_birth: string;
  observation: string;
  registered_by: number;
  course_id: number;
  course_turn_id: number;
  created_at: string;
  updated_at: string;
}

export interface Bank {
  id: number;
  name: string;
  abbreviation: string;
  created_at: string;
  updated_at: string;
}

export interface CourseTurnStudent {
  id: number;
  student_id: number;
  course_turn_id: number;
  enrolled_by: number;
  payment_id: number;
  start_date: string;
  created_at: string;
  updated_at: string;
  student: Student;
}

export interface Student {
  id: number;
  name: string;
  dni: string;
  email: string;
  department_id: number;
  address: string;
  phone: string;
  cellphone: string;
  date_of_birth: string;
  observation: string;
  registered_by: number;
  course_id: number;
  course_turn_id: number;
  created_at: string;
  updated_at: string;
}
