// Generated by https://quicktype.io

import { Department } from 'src/app/shared/interfaces/department.interface';

export interface Student {
  id: number;
  name: string;
  dni: string;
  email: string;
  department_id: number;
  address: string;
  phone: string;
  cellphone: string;
  observation: string;
  course_id: number;
  course_turn_id: number;
  signed_up: number;
  registered_by: number;
  registered_at: string;
  enrolled_by: EnrolledBy;
  enrolled_at: string;
  start_date: string;
  created_at: string;
  updated_at: string;
  department: Department;
  course_turn: CourseTurn;
  course: Course;
}

export interface Course {
  id: number;
  name: string;
  days?: string;
  created_at: string;
  updated_at: string;
}

export interface CourseTurn {
  id: number;
  course_id: number;
  turn_id: number;
  start_hour: string;
  end_hour: string;
  days: string;
  created_at: string;
  updated_at: string;
  turn: Turn;
}

export interface Turn {
  id: number;
  name: string;
  created_at: string;
  updated_at: string;
}

export interface EnrolledBy {
  id: number;
  name: string;
  email: string;
  email_verified_at: string;
  created_at: string;
  updated_at: string;
}
