// Generated by https://quicktype.io

export interface StudentDto {
  name: string;
  dni: string;
  email: string;
  department_id: number;
  address: string;
  phone: string;
  cellphone: string;
  observation: string;
  date_of_birth: string;
  course_id?: number;
  course_turn_id: number;
  registered_by?: number;
}
