// Generated by https://quicktype.io

export interface Student {
  id: number;
  name: string;
  dni: string;
  email: string;
  department_id: number;
  address: string;
  phone: string;
  cellphone: string;
  date_of_birth: string;
  observation: string;
  registered_by: RegisteredBy;
  course_id: number;
  course_turn_id: number;
  created_at: string;
  updated_at: string;
  department: Course;
  course_turn: CourseTurn;
  course: Course;
}

export interface Course {
  id: number;
  name: string;
  days?: string;
  created_at: string;
  updated_at: string;
}

export interface CourseTurn {
  id: number;
  course_id: number;
  turn_id: number;
  start_hour: string;
  end_hour: string;
  days: string;
  created_at: string;
  updated_at: string;
  turn: Course;
}

export interface RegisteredBy {
  id: number;
  name: string;
  email: string;
  email_verified_at: string;
  created_at: string;
  updated_at: string;
}
