// Generated by https://quicktype.io

import { Voucher } from "./voucher.interface";

export interface Report {
    vouchers: Voucher[];
    totales: Totales;
}

export interface Totales {
    Recibo: number;
    Boleta: number;
    Factura: number;
    Gastos: number;
}
