// Generated by https://quicktype.io

export interface Spending {
    id: number;
    description: string;
    amount: number;
    date: string;
    user_id: number;
    created_at: string;
    updated_at: string;
    user: User;
}

export interface User {
    id: number;
    name: string;
    email: string;
    email_verified_at: string;
    created_at: string;
    updated_at: string;
}
